# Generated by Django 5.1.1 on 2024-10-06 10:12

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_owner_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='level',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5), core.models.validateEqual], verbose_name='user level'),
        ),
    ]
