# Generated by Django 5.1.1 on 2024-10-06 11:13

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_owner_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='level',
            field=models.PositiveIntegerField(choices=[('Owner', 1), ('Supervisor', 2)], validators=[core.models.validateEqual], verbose_name='user level'),
        ),
    ]
