# Generated by Django 5.1.1 on 2024-10-06 11:32

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_owner_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='level',
            field=models.PositiveIntegerField(choices=[(0, 'Root'), (1, 'Owner'), (2, 'Supervisor')], validators=[core.models.validateEqual], verbose_name='user level'),
        ),
    ]
