# Generated by Django 5.1.2 on 2024-10-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='level',
            field=models.PositiveIntegerField(choices=[(0, 'Root'), (1, 'Owner'), (2, 'Supervisor')], verbose_name='user level'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='level',
            field=models.PositiveIntegerField(choices=[(0, 'Root'), (1, 'Owner'), (2, 'Supervisor')], verbose_name='user level'),
        ),
    ]
